version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=usuario
      - DATABASE_PASSWORD=contraseña
      - DATABASE_NAME=nombre_base_datos

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nombre_base_datos
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contraseña
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
