# Usa una imagen base de Python
FROM python:3.10-slim

# Define el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de tu proyecto al contenedor
COPY . /app

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto en el que corre tu aplicación
EXPOSE 5000

# Comando para iniciar tu aplicación
CMD ["python", "app/app.py"]
